services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      - GCP_PROJECT_ID=chronos-sandbox
      - GCP_ENGINE_ID=chronos_1748843978267
      - GOOGLE_APPLICATION_CREDENTIALS=/app/service-account.json
    volumes:
      # ホットリロード用（開発時のみ）
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./styles:/app/styles
      - ./public:/app/public

      # 設定ファイル
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./package.json:/app/package.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - ./tailwind.config.ts:/app/tailwind.config.ts

      # GCPサービスアカウントキーのマウント
      - ./.gcp/service-account.json:/app/service-account.json

    command: npm run dev
