services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=development
      # 開発時に必要な環境変数を追加できます
    volumes:
      # ホットリロード用（開発時のみ）
      - ./app:/app/app
      - ./components:/app/components
      - ./lib:/app/lib
      - ./styles:/app/styles
      - ./public:/app/public
      # 設定ファイル
      - ./tsconfig.json:/app/tsconfig.json
      - ./next.config.mjs:/app/next.config.mjs
      - ./package.json:/app/package.json
      - ./postcss.config.mjs:/app/postcss.config.mjs
      - ./tailwind.config.ts:/app/tailwind.config.ts
    command: npm run dev
