name: Deploy to Cloud Run

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  SERVICE_NAME: web
  REGION: asia-northeast1  # 東京リージョン

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}

    - name: Google Auth
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker
      run: |
        gcloud auth configure-docker asia-northeast1-docker.pkg.dev

    - name: Build and Push Container
      run: |
        docker build -t asia-northeast1-docker.pkg.dev/$PROJECT_ID/nextjs-repo/$SERVICE_NAME:${{ github.sha }} .
        docker push asia-northeast1-docker.pkg.dev/$PROJECT_ID/nextjs-repo/$SERVICE_NAME:${{ github.sha }}

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $SERVICE_NAME \
          --image=asia-northeast1-docker.pkg.dev/$PROJECT_ID/nextjs-repo/$SERVICE_NAME:${{ github.sha }} \
          --platform=managed \
          --region=$REGION \
          --allow-unauthenticated \
          --memory=1Gi \
          --cpu=1 \
          --min-instances=0 \
          --max-instances=10 \
          --concurrency=80 \
          --port=8080 \
          --set-env-vars="NODE_ENV=production"

    - name: Show Output URL
      run: |
        echo "サービスURL: $(gcloud run services describe $SERVICE_NAME --region=$REGION --format='value(status.url)')"
